#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Admin.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_PRODUCCION")]
	public partial class DataSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataSqlDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BD_PRODUCCIONConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_muestra_ubicacion_saec")]
		public ISingleResult<sp_muestra_ubicacion_saecResult> sp_muestra_ubicacion_saec([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string code_encriptado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code_encriptado);
			return ((ISingleResult<sp_muestra_ubicacion_saecResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_muestra_ubicacion_saec_2")]
		public ISingleResult<sp_muestra_ubicacion_saec_2Result> sp_muestra_ubicacion_saec_2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string code_encriptado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code_encriptado);
			return ((ISingleResult<sp_muestra_ubicacion_saec_2Result>)(result.ReturnValue));
		}
	}
	
	public partial class sp_muestra_ubicacion_saecResult
	{
		
		private int _Id;
		
		private string _Ubicacion;
		
		public sp_muestra_ubicacion_saecResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicacion", DbType="NVarChar(103) NOT NULL", CanBeNull=false)]
		public string Ubicacion
		{
			get
			{
				return this._Ubicacion;
			}
			set
			{
				if ((this._Ubicacion != value))
				{
					this._Ubicacion = value;
				}
			}
		}
	}
	
	public partial class sp_muestra_ubicacion_saec_2Result
	{
		
		private int _Id;
		
		private string _CamaraCongelamiento;
		
		private string _Estante;
		
		private System.Nullable<decimal> _Altura;
		
		private System.Nullable<decimal> _Fondo;
		
		private System.Nullable<int> _Palet;
		
		private System.Nullable<decimal> _PBascula;
		
		private System.Nullable<decimal> _PBrutos;
		
		private System.Nullable<decimal> _PNetos;
		
		private string _Partida;
		
		public sp_muestra_ubicacion_saec_2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CamaraCongelamiento", DbType="NVarChar(5)")]
		public string CamaraCongelamiento
		{
			get
			{
				return this._CamaraCongelamiento;
			}
			set
			{
				if ((this._CamaraCongelamiento != value))
				{
					this._CamaraCongelamiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estante", DbType="NVarChar(5)")]
		public string Estante
		{
			get
			{
				return this._Estante;
			}
			set
			{
				if ((this._Estante != value))
				{
					this._Estante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Altura", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> Altura
		{
			get
			{
				return this._Altura;
			}
			set
			{
				if ((this._Altura != value))
				{
					this._Altura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fondo", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> Fondo
		{
			get
			{
				return this._Fondo;
			}
			set
			{
				if ((this._Fondo != value))
				{
					this._Fondo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Palet", DbType="Int")]
		public System.Nullable<int> Palet
		{
			get
			{
				return this._Palet;
			}
			set
			{
				if ((this._Palet != value))
				{
					this._Palet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PBascula", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> PBascula
		{
			get
			{
				return this._PBascula;
			}
			set
			{
				if ((this._PBascula != value))
				{
					this._PBascula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PBrutos", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> PBrutos
		{
			get
			{
				return this._PBrutos;
			}
			set
			{
				if ((this._PBrutos != value))
				{
					this._PBrutos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNetos", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> PNetos
		{
			get
			{
				return this._PNetos;
			}
			set
			{
				if ((this._PNetos != value))
				{
					this._PNetos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Partida", DbType="NVarChar(50)")]
		public string Partida
		{
			get
			{
				return this._Partida;
			}
			set
			{
				if ((this._Partida != value))
				{
					this._Partida = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
